// <auto-generated />
using System;
using FitnessCoach.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessCoach.Api.Persistence.Migrations
{
    [DbContext(typeof(FitnessCoachDbContext))]
    [Migration("20260830055449_AddApplicationAccountOwnership")]
    partial class AddApplicationAccountOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<string>("Execution")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("execution");

                    b.Property<string>("MovementPattern")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("movement_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("safety");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("setup");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tracking_mode");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercises_category", "category IN ('Strength', 'Cardio')");

                            t.HasCheckConstraint("CK_exercises_movement_pattern", "movement_pattern IN ('Squat', 'Hinge', 'Lunge', 'HorizontalPush', 'VerticalPush', 'HorizontalPull', 'VerticalPull', 'Carry', 'CoreStability', 'ElbowFlexion', 'ElbowExtension', 'CalfRaise', 'Locomotion')");

                            t.HasCheckConstraint("CK_exercises_tracking_mode", "tracking_mode IN ('Repetitions', 'RepetitionsAndLoad', 'Duration', 'DistanceAndDuration', 'DistanceDurationAndLoad')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseAlias", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.HasKey("ExerciseId", "Alias");

                    b.ToTable("exercise_aliases", (string)null);
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseCatalogueState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CatalogueVersion")
                        .HasColumnType("integer")
                        .HasColumnName("catalogue_version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_status");

                    b.HasKey("Id");

                    b.ToTable("exercise_catalogue_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_catalogue_state_review_status", "review_status IN ('RequiresQualifiedReview', 'QualifiedReviewComplete')");

                            t.HasCheckConstraint("CK_exercise_catalogue_state_singleton", "id = 1");

                            t.HasCheckConstraint("CK_exercise_catalogue_state_version", "catalogue_version > 0");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseEquipment", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Equipment")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("equipment");

                    b.HasKey("ExerciseId", "Equipment");

                    b.ToTable("exercise_equipment", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_equipment_equipment", "equipment IN ('Bodyweight', 'Dumbbells', 'Barbell', 'Bench', 'SquatRack', 'CableMachine', 'ResistanceBands', 'CardioEquipment')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Muscle")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("muscle");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ExerciseId", "Muscle");

                    b.ToTable("exercise_muscles", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_muscles_muscle", "muscle IN ('Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms', 'Core')");

                            t.HasCheckConstraint("CK_exercise_muscles_role", "role IN ('Primary', 'Secondary')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Identity.ApplicationAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("application_accounts", (string)null);
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("experience");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit_system");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("training_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profiles_experience", "experience IN ('Beginner', 'Intermediate', 'Advanced')");

                            t.HasCheckConstraint("CK_training_profiles_unit_system", "unit_system IN ('Metric', 'Imperial')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileEquipment", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Equipment")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("equipment");

                    b.HasKey("ProfileId", "Equipment");

                    b.ToTable("training_profile_equipment", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profile_equipment_equipment", "equipment IN ('Bodyweight', 'Dumbbells', 'Barbell', 'Bench', 'SquatRack', 'CableMachine', 'ResistanceBands', 'CardioEquipment')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileGoal", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Goal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("goal");

                    b.HasKey("ProfileId", "Goal");

                    b.ToTable("training_profile_goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profile_goals_goal", "goal IN ('BuildStrength', 'BuildMuscle', 'GeneralFitness')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CorrectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrected_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("LastMutationId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_mutation_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("workout_name");

                    b.Property<Guid>("WorkoutPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_plan_id");

                    b.Property<int>("WorkoutPlanRevision")
                        .HasColumnType("integer")
                        .HasColumnName("workout_plan_revision");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.HasIndex("ProfileId", "StartedAt");

                    b.HasIndex("ProfileId", "Status")
                        .IsUnique()
                        .HasFilter("status = 'Active'");

                    b.HasIndex("ProfileId", "Status", "FinishedAt");

                    b.ToTable("workout_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_sessions_finished", "(status = 'Active' AND finished_at IS NULL) OR (status = 'Completed' AND finished_at IS NOT NULL)");

                            t.HasCheckConstraint("CK_workout_sessions_name", "length(btrim(workout_name)) > 0");

                            t.HasCheckConstraint("CK_workout_sessions_revision", "revision > 0");

                            t.HasCheckConstraint("CK_workout_sessions_status", "status IN ('Active', 'Completed')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSessionExercise", b =>
                {
                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("exercise_name");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean")
                        .HasColumnName("is_skipped");

                    b.Property<int?>("MaximumRepetitions")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_repetitions");

                    b.Property<int?>("MinimumRepetitions")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_repetitions");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("PlannedSets")
                        .HasColumnType("integer")
                        .HasColumnName("planned_sets");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.PrimitiveCollection<string[]>("PrimaryMuscles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("primary_muscles");

                    b.Property<decimal?>("TargetDistanceMetres")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_distance_metres");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("target_duration_seconds");

                    b.Property<decimal?>("TargetLoadKilograms")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_load_kilograms");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tracking_mode");

                    b.HasKey("WorkoutSessionId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("workout_session_exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_session_exercises_planned_sets", "planned_sets BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_workout_session_exercises_position", "position >= 0 AND position < 20");

                            t.HasCheckConstraint("CK_workout_session_exercises_tracking_mode", "tracking_mode IN ('Repetitions', 'RepetitionsAndLoad', 'Duration', 'DistanceAndDuration', 'DistanceDurationAndLoad')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSessionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualDistanceMetres")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("actual_distance_metres");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration_seconds");

                    b.Property<decimal?>("ActualLoadKilograms")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("actual_load_kilograms");

                    b.Property<int?>("ActualRepetitions")
                        .HasColumnType("integer")
                        .HasColumnName("actual_repetitions");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId", "ExerciseId", "Position");

                    b.ToTable("workout_session_sets", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_session_sets_completion", "(is_completed AND completed_at IS NOT NULL) OR (NOT is_completed AND completed_at IS NULL)");

                            t.HasCheckConstraint("CK_workout_session_sets_distance", "actual_distance_metres IS NULL OR actual_distance_metres > 0 AND actual_distance_metres <= 1000000");

                            t.HasCheckConstraint("CK_workout_session_sets_duration", "actual_duration_seconds IS NULL OR actual_duration_seconds BETWEEN 1 AND 86400");

                            t.HasCheckConstraint("CK_workout_session_sets_load", "actual_load_kilograms IS NULL OR actual_load_kilograms > 0 AND actual_load_kilograms <= 2000");

                            t.HasCheckConstraint("CK_workout_session_sets_position", "position >= 0 AND position < 20");

                            t.HasCheckConstraint("CK_workout_session_sets_repetitions", "actual_repetitions IS NULL OR actual_repetitions BETWEEN 1 AND 1000");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Workouts.WorkoutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "UpdatedAt");

                    b.ToTable("workout_plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_plans_name", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("CK_workout_plans_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Workouts.WorkoutPlanExercise", b =>
                {
                    b.Property<Guid>("WorkoutPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_plan_id");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("MaximumRepetitions")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_repetitions");

                    b.Property<int?>("MinimumRepetitions")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_repetitions");

                    b.Property<int>("PlannedSets")
                        .HasColumnType("integer")
                        .HasColumnName("planned_sets");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal?>("TargetDistanceMetres")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_distance_metres");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("target_duration_seconds");

                    b.Property<decimal?>("TargetLoadKilograms")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_load_kilograms");

                    b.HasKey("WorkoutPlanId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("workout_plan_exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_plan_exercises_planned_sets", "planned_sets >= 1 AND planned_sets <= 20");

                            t.HasCheckConstraint("CK_workout_plan_exercises_position", "position >= 0 AND position < 20");

                            t.HasCheckConstraint("CK_workout_plan_exercises_repetitions", "(minimum_repetitions IS NULL OR minimum_repetitions BETWEEN 1 AND 1000) AND (maximum_repetitions IS NULL OR maximum_repetitions BETWEEN 1 AND 1000) AND (minimum_repetitions IS NULL OR maximum_repetitions IS NULL OR minimum_repetitions <= maximum_repetitions)");

                            t.HasCheckConstraint("CK_workout_plan_exercises_target_distance", "target_distance_metres IS NULL OR target_distance_metres > 0 AND target_distance_metres <= 1000000");

                            t.HasCheckConstraint("CK_workout_plan_exercises_target_duration", "target_duration_seconds IS NULL OR target_duration_seconds BETWEEN 1 AND 86400");

                            t.HasCheckConstraint("CK_workout_plan_exercises_target_load", "target_load_kilograms IS NULL OR target_load_kilograms > 0 AND target_load_kilograms <= 2000");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseAlias", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany("Aliases")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseEquipment", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany("RequiredEquipment")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseMuscle", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany("Muscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfile", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Identity.ApplicationAccount", null)
                        .WithOne("Profile")
                        .HasForeignKey("FitnessCoach.Api.Features.Profiles.TrainingProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileEquipment", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany("AvailableEquipment")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileGoal", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany("Goals")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSession", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessCoach.Api.Features.Workouts.WorkoutPlan", null)
                        .WithMany()
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSessionExercise", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessCoach.Api.Features.Sessions.WorkoutSession", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSessionSet", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Sessions.WorkoutSessionExercise", null)
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Workouts.WorkoutPlan", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Workouts.WorkoutPlanExercise", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessCoach.Api.Features.Workouts.WorkoutPlan", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.Exercise", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Muscles");

                    b.Navigation("RequiredEquipment");
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Identity.ApplicationAccount", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfile", b =>
                {
                    b.Navigation("AvailableEquipment");

                    b.Navigation("Goals");
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Sessions.WorkoutSessionExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Workouts.WorkoutPlan", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
