// <auto-generated />
using System;
using FitnessCoach.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessCoach.Api.Persistence.Migrations
{
    [DbContext(typeof(FitnessCoachDbContext))]
    [Migration("20260826023738_AddTrainingProfiles")]
    partial class AddTrainingProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("experience");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit_system");

                    b.HasKey("Id");

                    b.ToTable("training_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profiles_experience", "experience IN ('Beginner', 'Intermediate', 'Advanced')");

                            t.HasCheckConstraint("CK_training_profiles_unit_system", "unit_system IN ('Metric', 'Imperial')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileEquipment", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Equipment")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("equipment");

                    b.HasKey("ProfileId", "Equipment");

                    b.ToTable("training_profile_equipment", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profile_equipment_equipment", "equipment IN ('Bodyweight', 'Dumbbells', 'Barbell', 'Bench', 'SquatRack', 'CableMachine', 'ResistanceBands', 'CardioEquipment')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileGoal", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Goal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("goal");

                    b.HasKey("ProfileId", "Goal");

                    b.ToTable("training_profile_goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profile_goals_goal", "goal IN ('BuildStrength', 'BuildMuscle', 'GeneralFitness')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileEquipment", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany("AvailableEquipment")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileGoal", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany("Goals")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfile", b =>
                {
                    b.Navigation("AvailableEquipment");

                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
