// <auto-generated />
using System;
using FitnessCoach.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessCoach.Api.Persistence.Migrations
{
    [DbContext(typeof(FitnessCoachDbContext))]
    [Migration("20260827031826_AddExerciseCatalogue")]
    partial class AddExerciseCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<string>("Execution")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("execution");

                    b.Property<string>("MovementPattern")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("movement_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("safety");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("setup");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("TrackingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tracking_mode");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercises_category", "category IN ('Strength', 'Cardio')");

                            t.HasCheckConstraint("CK_exercises_movement_pattern", "movement_pattern IN ('Squat', 'Hinge', 'Lunge', 'HorizontalPush', 'VerticalPush', 'HorizontalPull', 'VerticalPull', 'Carry', 'CoreStability', 'ElbowFlexion', 'ElbowExtension', 'CalfRaise', 'Locomotion')");

                            t.HasCheckConstraint("CK_exercises_tracking_mode", "tracking_mode IN ('Repetitions', 'RepetitionsAndLoad', 'Duration', 'DistanceAndDuration', 'DistanceDurationAndLoad')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseAlias", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.HasKey("ExerciseId", "Alias");

                    b.ToTable("exercise_aliases", (string)null);
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseCatalogueState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CatalogueVersion")
                        .HasColumnType("integer")
                        .HasColumnName("catalogue_version");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_status");

                    b.HasKey("Id");

                    b.ToTable("exercise_catalogue_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_catalogue_state_review_status", "review_status IN ('RequiresQualifiedReview', 'QualifiedReviewComplete')");

                            t.HasCheckConstraint("CK_exercise_catalogue_state_singleton", "id = 1");

                            t.HasCheckConstraint("CK_exercise_catalogue_state_version", "catalogue_version > 0");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseEquipment", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Equipment")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("equipment");

                    b.HasKey("ExerciseId", "Equipment");

                    b.ToTable("exercise_equipment", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_equipment_equipment", "equipment IN ('Bodyweight', 'Dumbbells', 'Barbell', 'Bench', 'SquatRack', 'CableMachine', 'ResistanceBands', 'CardioEquipment')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Muscle")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("muscle");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ExerciseId", "Muscle");

                    b.ToTable("exercise_muscles", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_muscles_muscle", "muscle IN ('Quadriceps', 'Hamstrings', 'Glutes', 'Calves', 'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms', 'Core')");

                            t.HasCheckConstraint("CK_exercise_muscles_role", "role IN ('Primary', 'Secondary')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("experience");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit_system");

                    b.HasKey("Id");

                    b.ToTable("training_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profiles_experience", "experience IN ('Beginner', 'Intermediate', 'Advanced')");

                            t.HasCheckConstraint("CK_training_profiles_unit_system", "unit_system IN ('Metric', 'Imperial')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileEquipment", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Equipment")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("equipment");

                    b.HasKey("ProfileId", "Equipment");

                    b.ToTable("training_profile_equipment", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profile_equipment_equipment", "equipment IN ('Bodyweight', 'Dumbbells', 'Barbell', 'Bench', 'SquatRack', 'CableMachine', 'ResistanceBands', 'CardioEquipment')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileGoal", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Goal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("goal");

                    b.HasKey("ProfileId", "Goal");

                    b.ToTable("training_profile_goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_training_profile_goals_goal", "goal IN ('BuildStrength', 'BuildMuscle', 'GeneralFitness')");
                        });
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseAlias", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany("Aliases")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseEquipment", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany("RequiredEquipment")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.ExerciseMuscle", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Exercises.Exercise", null)
                        .WithMany("Muscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileEquipment", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany("AvailableEquipment")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfileGoal", b =>
                {
                    b.HasOne("FitnessCoach.Api.Features.Profiles.TrainingProfile", null)
                        .WithMany("Goals")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Exercises.Exercise", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Muscles");

                    b.Navigation("RequiredEquipment");
                });

            modelBuilder.Entity("FitnessCoach.Api.Features.Profiles.TrainingProfile", b =>
                {
                    b.Navigation("AvailableEquipment");

                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
